### ISSUE TITLE
Add lint staged + pre-commit

### ISSUE THREAD

**Issue by julioxavierr** [vorcigernix/sbkshack19#1]
This will improve your code readability, also is nice to have a pattern.
You can also add custom rules to prevent some things you don't want to push to your repo, like `console.log`.

**Comment by vorcigernix** [comment]
Thanks, I need to read something about linter implementation in javascript, I'll fix that later.

**Comment by vorcigernix** [comment]
Ok, read some minimum. What would be your weapon of choice here? Eslint? Standard? Prettier?

**Comment by julioxavierr** [comment]
Eslint + prettier + lint staged + pre-commit
Look at this repo https://github.com/entria/entria-fullstack

**Comment by vorcigernix** [comment]
Got it. I will introduce it in code gradually, now I am fighting opengraph. Thanks for suggestion.
