### ISSUE TITLE
Add .env.example

### ISSUE THREAD

**Issue by julioxavierr** [vorcigernix/sbkshack19#2]
I see here that you're using env.
https://github.com/vorcigernix/sbkshack19/blob/a582c00f05c88fb10f903f17079b0756cc8a718b/src/Schedule.js#L7

You can add an example of `.env` file called `.env.example` without any keys. This will make easier to run your project.

```
REACT_APP_SPACE_ID=
REACT_APP_ACCESS_TOKEN=
```

Also, add this info on your README, how we configure this? How can we generate these keys?

**Comment by vorcigernix** [comment]
Hopefully fixed.
