### ISSUE TITLE
Think in edge cases

### ISSUE THREAD

**Issue by julioxavierr** [vorcigernix/sbkshack19#5]
Looking at your code seems that you don't treat edge cases... When something that you don't expect happens. Example:

https://github.com/vorcigernix/sbkshack19/blob/a582c00f05c88fb10f903f17079b0756cc8a718b/src/Schedule.js#L41

What should happen if `eventItem` or `eventItem.sys` is `undefined` or `null` here? For now, it would break your code.

I like to use `idx`.

**Comment by vorcigernix** [comment]
I understand comment about liability to null values, it really stop working in other cases (I added AND operator to some places to catch that). What is the suggestion? To use my own id numbering?

**Comment by vorcigernix** [comment]
Oh, this: https://github.com/facebookincubator/idx right? Wasn't aware of that.

**Comment by julioxavierr** [comment]
Yep. That lib will make easier to treat these situations.

**Comment by vorcigernix** [comment]
I fixed that without idx (I generally want to introduce as little dependencies as possible).  There is still code expecting value (as this value is mandatory in CMS). It will probably never fail on this (data will be either absent generally, thus caught by exception or they will be there), but from the edge case perspective, this is still code which can fail. Do you think it is worth managing?

**Comment by julioxavierr** [comment]
Software generally will always have edge cases and that's fine. The idea is to treat the most common cases then move on, you can improve the other ones in the future or as they happen.
